keys:
  - &primary age108tyuha7ad6jzyt25h7uqd3sege3yezu6sr4qmnsg80yrvuzhuyqc4qww5
creation_rules:
  - path_regex: .*secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *primary
  - path_regex: .*$
    key_groups:
    - age:
      - *primary
