keys:
  - &primary age1sdgx44evfe62xm7kmrl2hs3u3c2f3ltxqy4mpry5w45v9qakmyts3rl75d
  - &server age103fjfz87fg2aye2e6vwdgneqgmkdea9rw4gy7xxr298cm890guksv99ml5
creation_rules:
  - path_regex: .*secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *primary
      - *server
  - path_regex: .*$
    key_groups:
    - age:
      - *primary
      - *server
