# [plugin]
# prepend_preloaders = [ { mime = "image/*", run = "noop" }, { mime = "application/pdf", run = "noop" } ]
# prepend_previewers = [ { mime = "image/*", run = "noop" }, { mime = "application/pdf", run = "noop" } ]
[preview]
# max_height=300

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"
