[[language]]
name = "go"
language-servers = ["gopls"]

[[language]]
name = "typst"
language-servers = ["tinymist"]

[language-server.tinymist]
command = "tinymist"
# config = {}
config = { exportPdf = "onSave", outputPath = "$root/target/$dir/$name"}
